project_name: harbor

builds:
- main: ./cmd/harbor/main.go
  binary: ./harbor
  env:
    - CGO_ENABLED=0
  ldflags:
    - -w -s -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.GitCommit={{.FullCommit}}
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
    - arm
  ignore: 
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot: 
  name_template: "{{ .Tag }}-next"
release:
  name_template: "Harbor {{.Tag}}"
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
