project_name: harbor

builds:
- main: ./cmd/harbor
  binary: ./harbor
  env:
    - CGO_ENABLED=0
  ldflags:
    - -w -s -X github.com/goharbor/harbor-cli/cmd/harbor/internal/version.GitCommit={{.FullCommit}}
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
    - arm
  ignore: 
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64
archives:
- format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
release:
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
